### PR TITLE
add seesion 4

### PR DESCRIPTION
**Pull request by ShengMatthewLin**
Add examples and part of tutorial materials

### CODE REVIEW

**Comment by jvictorchen** [comment]
Could you remove the .Rhistory and .~lock.MA_1977_1980.xls files? You can add them to .gitignore.

**Comment by jvictorchen** [comment]
seesion -> session

**Comment by jvictorchen** [comment]
Could you rename "Pandas Lecture.ipynb" to "session4.ipynb"? Better avoid spaces in file names

**Comment by ShengMatthewLin** [comment]
Add more materials

**Pull request merged**
